#!/usr/bin/env bash

input_dir=$1
output_dir=$2

paste -d '?' <(gzip -cd $input_dir/odd_training.h.gz) <(gzip -cd $input_dir/odd_training.m.gz) | shuf > $output_dir/odd_train.temp
awk -v FS="?" '{print $1}' $output_dir/odd_train.temp | gzip > $output_dir/shuf_odd_training.h.gz
awk -v FS="?" '{print $2}' $output_dir/odd_train.temp | gzip > $output_dir/shuf_odd_training.m.gz
rm $output_dir/odd_train.temp
gzip -cd $output_dir/shuf_odd_training.m.gz | shuf | gzip > $output_dir/shufx2_odd_training.m.gz

paste -d '?' <(gzip -cd $input_dir/even_training.h.gz) <(gzip -cd $input_dir/even_training.m.gz) | shuf > $output_dir/even_train.temp
awk -v FS="?" '{print $1}' $output_dir/even_train.temp | gzip > $output_dir/shuf_even_training.h.gz
awk -v FS="?" '{print $2}' $output_dir/even_train.temp | gzip > $output_dir/shuf_even_training.m.gz
rm $output_dir/even_train.temp
gzip -cd $output_dir/shuf_even_training.m.gz | shuf | gzip > $output_dir/shufx2_even_training.m.gz

paste -d '?' <(gzip -cd $input_dir/odd_validation.h.gz) <(gzip -cd $input_dir/odd_validation.m.gz) | shuf > $output_dir/odd_validation.temp
awk -v FS="?" '{print $1}' $output_dir/odd_validation.temp | gzip > $output_dir/shuf_odd_validation.h.gz
awk -v FS="?" '{print $2}' $output_dir/odd_validation.temp | gzip > $output_dir/shuf_odd_validation.m.gz
rm $output_dir/odd_validation.temp
gzip -cd $output_dir/shuf_odd_validation.m.gz | shuf | gzip > $output_dir/shufx2_odd_validation.m.gz

paste -d '?' <(gzip -cd $input_dir/even_validation.h.gz) <(gzip -cd $input_dir/even_validation.m.gz) | shuf > $output_dir/even_validation.temp
awk -v FS="?" '{print $1}' $output_dir/even_validation.temp | gzip > $output_dir/shuf_even_validation.h.gz
awk -v FS="?" '{print $2}' $output_dir/even_validation.temp | gzip > $output_dir/shuf_even_validation.m.gz
rm $output_dir/even_validation.temp
gzip -cd $output_dir/shuf_even_validation.m.gz | shuf | gzip > $output_dir/shufx2_even_validation.m.gz

paste -d '?' <(gzip -cd $input_dir/odd_test.h.gz) <(gzip -cd $input_dir/odd_test.m.gz) | shuf > $output_dir/odd_test.temp
awk -v FS="?" '{print $1}' $output_dir/odd_test.temp | gzip > $output_dir/shuf_odd_test.h.gz
awk -v FS="?" '{print $2}' $output_dir/odd_test.temp | gzip > $output_dir/shuf_odd_test.m.gz
rm $output_dir/odd_test.temp
gzip -cd $output_dir/shuf_odd_test.m.gz | shuf | gzip > $output_dir/shufx2_odd_test.m.gz

paste -d '?' <(gzip -cd $input_dir/even_test.h.gz) <(gzip -cd $input_dir/even_test.m.gz) | shuf > $output_dir/even_test.temp
awk -v FS="?" '{print $1}' $output_dir/even_test.temp | gzip > $output_dir/shuf_even_test.h.gz
awk -v FS="?" '{print $2}' $output_dir/even_test.temp | gzip > $output_dir/shuf_even_test.m.gz
rm $output_dir/even_test.temp
gzip -cd $output_dir/shuf_even_test.m.gz | shuf | gzip > $output_dir/shufx2_even_test.m.gz
